project_name: go-pivnet

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: pivotal-cf
    name: go-pivnet
  draft: true

